### ISSUE TITLE
一人称

### ISSUE THREAD

**Issue by negipo** [ktnyt/CGCallTable#1]
こんにちは。いつも利用させていただいています。
アイドルの一人称を知りたくて立ち上げてしまうことがたまにあるので、CallerとCalleeが同じ行があると嬉しいです。

**Comment by ktnyt** [comment]
お使いいただきありがとうございます。一人称について直近の利用では不要かと考えていましたがせっかくですのでデータを追加致します。早ければ今晩中にもデータを流し込みますのでしばしお待ちいただければ幸いです。

**Comment by ktnyt** [comment]
一人称データを追加しGitHub Pagesの方に反映致しました、ニコニコ大百科にあるものに準拠しているため漏れなどがあるかもしれません。もし問題等がありましたらお知らせ頂ければ幸いです。
